### ISSUE TITLE
Autoflush on collection post

### ISSUE THREAD

**Issue by emilecaron** [ColtonProvias/sqlalchemy-jsonapi#13]
I've had this issue where sqlalchemy session would get flushed in the middle of relationships setters. Since data attributes are not yet set at that point, the sql insert query fails, aborting the post request.
Disabling autoflush fixed this: https://github.com/emilecaron/sqlalchemy-jsonapi/commit/17742debde772b51d3af86b2adcd21c213e658a1

I'm handling some fairly complex models, with a lot of validation and relations so this bug should not concern most users.

**Comment by ColtonProvias** [comment]
That actually fixes an issue I've had just yesterday.  So if you don't mind, can I implement your fix in the codebase, crediting you of course?

A bug is a bug and should be addressed whenever possible.  Thank you for this!
