### ISSUE TITLE
FlaskJSONAPI is None/doesn't import properly?

### ISSUE THREAD

**Issue by Datamance** [ColtonProvias/sqlalchemy-jsonapi#18]
Doesn't appear to import properly:

Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    os.getenv('MY_APP_CONFIG', 'default'), app, database)
  File "/Users/ricorodriguez/Desktop/git/project/my_app/webapp.py", line 25, in setup_app
    return FlaskJSONAPI(app, database)
TypeError: 'NoneType' object is not callable

Here's the dir() output for the sqlalchemy_jsonapi module:

['ALL_PERMISSIONS', 'AttributeActions', 'Endpoint', 'FlaskJSONAPI', 'INTERACTIVE_PERMISSIONS', 'JSONAPI', 'Method', 'Permissions', 'RelationshipActions', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'attr_descriptor', 'constants', 'errors', 'permission_test', 'relationship_descriptor', 'serializer']

Looks fine to me - what could be going on here?

**Comment by Datamance** [comment]
update: this is definitely a python 3 import based issue. Here's my output when I try to run my manager with python3:

  File "manage.py", line 5, in <module>
    from flask.ext.script import Manager
ImportError: No module named 'flask'

**Comment by Datamance** [comment]
@ColtonProvias - figured out the environment problems, there's quite a bit of setup involved with virtual environments.

My bet is that a lot of people want to use what you have here - this project would greatly benefit from enhanced documentation. In particular, I'm interested if I can use SQLAlchemy(app).Model rather than the declarative base during setup.

**Comment by ColtonProvias** [comment]
When using FlaskJSONAPI, it uses `SQLAlchemy(app)` as its second argument:

```py
db = SQLAlchemy(app)
api = FlaskJSONAPI(app, db)
```

I just need to sit myself down and force myself to finish documenting it.  I've also got a collection of updates for this project backlogged as well too since we use it in production on one of our products.
