### ISSUE TITLE
FlaskJSONAPI doesn't connect to postgres

### ISSUE THREAD

**Issue by Datamance** [ColtonProvias/sqlalchemy-jsonapi#19]
using a flask shell manager I see this:
>>> db.engine
Engine(postgres://localhost:5432/opengov)
>>> api.serializer.prefix
'http://localhost:5000/api'
>>> app.config['SERVER_NAME']
'localhost:5000'
>>> app.config['SQLALCHEMY_DATABASE_URI']
'postgres://localhost:5432/opengov'`

My init_db manager command initalizes the tables just fine.

Everything seems to be configured properly, yet I still get this error when I hit http://localhost:5000/api/citizen (that's the name of my sqlalchemy table/orm; I chose not to inflect it for the sake of simplicity while trying to figure out how your library works):

`{
  "errors": [
    {
      "id": "51a8b3de-b1fc-41b9-b1c5-810f77a426d7",
      "status": 404,
      "detail": "This backend has not been configured to handle resources of type citizen.",
      "title": "Resource Type Not Found",
      "code": "resource_type_not_found"
    }
  ]
}`

Any idea what's off here?

**Comment by ColtonProvias** [comment]
I'm assuming that you are using Flask-SQLAlchemy as well.

```py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'psycopg2+postgres://localhost:5432/opengov'
app.config['SERVER_NAME'] = 'localhost:5000'
db = SQLAlchemy(app)
api = FlaskJSONAPI(app, db)
```

The models should all be extending db.Model.

**Comment by Datamance** [comment]
That I am! (using flask_sqlalchemy, as well as the derived db.Model to define all my models.)

I think I have a problem with my virtual environment though, as I'm getting this error:

sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:psycopg2.postgres

Probably looking for the wrong psycopg2. I'm new to this whole virtualenv thing so I gotta do a bit more reading as to how to manage my dependencies properly.

**Comment by Datamance** [comment]
Ack, nope, I just typed "postgres" instead of "postgresql" :)

My configuration is still bunk though. Still getting the 404 when I should be getting a 204 (no content)

The struggle continues... I'll let you know if I can diagnose what's going on and ask for help when it's appropriate!

**Comment by Datamance** [comment]
Closing this, as the issue is moot :)
