### ISSUE TITLE
POST Collection broken in 4.0.8?

### ISSUE THREAD

**Issue by Datamance** [ColtonProvias/sqlalchemy-jsonapi#20]
https://github.com/ColtonProvias/sqlalchemy-jsonapi/commit/c8307459e8a16e677d019dd0aae61f5aab0790f2

Looks like you had it fixed here, but currently I'm throwing a 404 when I POST to the same URL that I successfully GET from.

**Comment by ColtonProvias** [comment]
What is the error message returned in the 404?  The only times it should throw a 404 are for `resource_not_found`, `related_resource_not_found`, `relationship_not_found`, and `resource_type_not_found`.

**Comment by Datamance** [comment]
I lied! Had the wrong host in Postman.

By the way. THIS IS AMAZING.

**Comment by ColtonProvias** [comment]
Glad you got it fixed!

I'm glad to have created this library as well.  It's saved me many hours of time.  Plus, since it follows a set boilerplate, it becomes easier for my team to move between projects as the APIs all follow the same format.
