### ISSUE TITLE
does not allow the use of custom attribute Column names

### ISSUE THREAD

**Issue by bastianl** [ColtonProvias/sqlalchemy-jsonapi#4]
In some cases it has been useful for us to override the name of an attribute on a model with the `name` keyword argument of the Column. However, `dump_column` is [inspecting the `__table__`](https://github.com/ColtonProvias/sqlalchemy-jsonapi/blob/master/sqlalchemy_jsonapi.py#L199) attribute of each model instead of the class itself (see [runtime inspection](http://docs.sqlalchemy.org/en/latest/core/inspection.html)). As the use of Column classes perpetuate through the code a bit I'm not sure how easy a fix for this would be, but as you mentioned you are making significant changes to conform with the RC3 spec I hope this is timely. Am also happy to help out, thanks!

Cheers.

**Comment by oshikryu** [comment]
I'm also having trouble getting the correct column names when trying to serialize my sqlalchemy objects. In my case, I am using a polymorphic table structure and neither the base table or its subtable columns are being returned after serialization.

**Comment by ColtonProvias** [comment]
I know I'm delayed on this; been busy the past few weeks, but my schedule has opened up more again so I can put more focus on meeting the latest version of the spec again.  Pretty much the entire thing is being rebuilt from the ground up to be more customizable but retain the ease of implementation.  I'll definitely be taking this into account the next few days as I rewrite the core serializer!

**Comment by ColtonProvias** [comment]
The new version does not depend on Column classes as much and inspects orm descriptors instead of columns itself on the table.
