### ISSUE TITLE
Mismatched function argument types.

### ISSUE THREAD

**Issue by tvaughan** [ColtonProvias/sqlalchemy-jsonapi#5]
According to [the documentation](http://sqlalchemy-jsonapi.readthedocs.org/en/latest/quickstart.html#serialization), a call to `get_collection` should look like:

    serializer.get_collection(db.session, {}, 'users')

Where the string `users` is eventually passed to the `inject_model` decorator which looks like:

    def wrapped(serializer, session, data, params):
        api_type = params.pop('api_type')

Currently this is located at: https://github.com/ColtonProvias/sqlalchemy-jsonapi/blob/master/sqlalchemy_jsonapi/serializer.py#L196

So `params` will be the string `users` in the example above. It looks like the expectation is that `params` should be a dict of keyword arguments, like:

    def wrapped(serializer, session, data, **params):
        api_type = params.pop('api_type')

However, `get_collection` looks like:

    def get_collection(self, session, query, model):

There is no `api_type` keyword argument. This assumption is made by other, similar functions too.

This:

    def wrapped(serializer, session, data, api_type):

worked for me. It seems like api_type can't be optional (and therefore should be a positional argument).

I didn't see a coverage report in the Travis CI output. I think I see where this is covered in the tests. However I'm baffled by how this could be covered **and** pass.

**Comment by ColtonProvias** [comment]
Currently fixing this.  It's an artifact from the project this library was pulled from.  Correction will be released in 2.0.0 today.

**Comment by ColtonProvias** [comment]
This has now been fixed and released.  The coverage I will implement soon into Travis-CI.

**Comment by tvaughan** [comment]
@ColtonProvias Thanks! Works for me.
