### ISSUE TITLE
cannot import name make_response

### ISSUE THREAD

**Issue by Meph-** [ColtonProvias/sqlalchemy-jsonapi#6]
Hi,
I'm trying to test your package, but I have problem with import make_response method from flask, because python is trying import the module from /sqlalchemy-jsonapi/flask.py.

Code:

    from flask import Flask
    from flask.ext.sqlalchemy import SQLAlchemy
    from sqlalchemy_jsonapi import FlaskJSONAPI
    app = Flask(__name__)
    db = SQLAlchemy(app)
    api = FlaskJSONAPI(app, db)
    @app.route("/")
    def hello():
         return "Hello World!"
    if __name__ == "__main__":
        app.run(debug=True)

Error:

    Traceback (most recent call last):
      File "D:/workspace/web_development/project/restfull-test/application.py", line 3, in <module>
        from sqlalchemy_jsonapi import FlaskJSONAPI
      File "C:\Python27\lib\site-packages\sqlalchemy_jsonapi\__init__.py", line 1, in <module>
        from .flask import FlaskJSONAPI
      File "C:\Python27\lib\site-packages\sqlalchemy_jsonapi\flask.py", line 14, in <module>
        from flask import make_response, request
    ImportError: cannot import name make_response

**Comment by ColtonProvias** [comment]
As a Python 3.x developer, I forgot about Python 2.x's import behavior.  Sorry about that!  I'll get that fixed ASAP.

**Comment by Datamance** [comment]
@ColtonProvias I think there might still be import issues - I'm unable to even import FlaskJSONAPI from the sqlalchemy_jsonapi package at all. Introspecting the module shows that the name binding is there, but it evaluates to NoneType so it throws a TypeError when I try to call it with app & database.
